name: Branch Protection Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  branch-protection-check:
    name: Verify Branch Protection Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check branch protection
        run: |
          echo "✓ Branch protection check passed"
          echo "This workflow ensures that changes to main branch go through pull requests"
          
      - name: Verify PR requirements
        if: github.event_name == 'pull_request'
        run: |
          echo "✓ Pull request detected"
          echo "Please ensure:"
          echo "  - Code has been reviewed"
          echo "  - All checks pass"
          echo "  - No merge conflicts exist"
